# Focus on navigation and modifiers only
extra-keys = [ \
  ['ESC', 'CTRL', 'ALT', 'HOME', 'UP', 'END', 'PGUP'], \
  ['TAB', 'SHIFT', 'DRAWER', 'LEFT', 'DOWN', 'RIGHT', 'PGDN'] \
]

# Keep the scale slightly smaller for a clean look
extra-keys-text-scale = 0.7
