# Focus on navigation and modifiers only
extra-keys = [ \
  ['ESC', 'TAB', 'CTRL', 'ALT', 'UP', 'HOME', 'PGUP'], \
  ['LEFT', 'DOWN', 'RIGHT', 'SHIFT', 'END', 'PGDN', 'DRAWER'] \
]

# Keep the scale slightly smaller for a clean look
extra-keys-text-scale = 0.7
